### PR TITLE
#162554289 A feature for allowing users to post answers to various questions(UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a form for submitting answers to questions

### Description of Task to be completed?
Have the following goals achieved:
1. The answer form should contains all details to allow ease of answering the question
2. The page should be simple but detailed
4. The page should be responsive
5. The page should be appealing to the user

### How should this be manually tested?
After cloning or forking the repo open the answer.html file from a browser

### Screenshots
screenshot from 2018-12-12 14-31-43
screenshot from 2018-12-12 14-32-32

### What is the relevant pivotal tracker stories?
#162554289

### CODE REVIEW

**Comment by munniomer** [comment]
@Ogutu-Brian  thumbs up

**Comment by Ogutu-Brian** [comment]
> @Ogutu-Brian thumbs up

Thanks @munniomer , you have helped a great deal

**Comment by Siffersari** [comment]
Great work. I love how you combined your colors. Really daring. I am challenged.

**Comment by MurungaKibaara** [comment]
Wow! This is amazing!!!!!!!

**Comment by a-braham** [comment]
This is amazing man..kudos

**Comment by Bakley** [comment]
Your JS is great and simple, how are you committing your CSS though? But otherwise awesome Job Man

**Comment by Ogutu-Brian** [comment]
> Great work. I love how you combined your colors. Really daring. I am challenged.

Thanks @Siffersari . On combination of colors, I chose teal, my favorite, and a shade of teal, I'm poor at colors so I wanted to stick to those lest I mess up the entire design

**Comment by Ogutu-Brian** [comment]
> Wow! This is amazing!!!!!!!

Thanks @MurungaKibaara

**Comment by Ogutu-Brian** [comment]
> This is amazing man..kudos
Thanks @a-braham

**Comment by Ogutu-Brian** [comment]
> Your JS is great and simple, how are you committing your CSS though? But otherwise awesome Job Man

Thanks @Bakley . I created a template css in gh-pages, then whenever I alter it to suit a feature, then the commits are tagged to that feature, it it affects other features you can include multiple story ids to reflect in those various stories as follows [#TRACKER_STORY_ID],[#TRACKER_STORY_ID] or [#TRACKER_STORY_ID] [#TRACKER_STORY_ID] , that way, a commit message with a given ID will not reflect in another story

**Comment by jackiegitari1234** [comment]
Wow..great

**Comment by Ogutu-Brian** [comment]
> Wow..great

Thanks @jackiegitari1234

**Pull request merged**
