### PR TITLE
#162554108 A Button feature for deleting questions by a user from stackOverflow-Lite(UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a button for deleting questions posted by a user

### Description of Task to be completed?
Have the following goals achieved:
1. The button should be of the correct size
2. The button events should be correctly handled by an external js file
3. The button color should match with the platform's theme
4. The page for rendering the feature should be responsive

### How should this be manually tested?
After cloning or forking the repo open the question.html file from a browser

### Screenshots
screenshot from 2018-12-12 12-27-31
screenshot from 2018-12-12 12-41-47

### What is the relevant pivotal tracker stories?
#162554108

### CODE REVIEW

**Comment by a-braham** [comment]
Kudos on the responsiveness of the app @Ogutu-Brian

**Comment by Ogutu-Brian** [comment]
> Kudos on the responsiveness of the app @Ogutu-Brian

Thanks @a-braham !

**Comment by Bakley** [comment]
Awesome Job

**Comment by munniomer** [comment]
It is beautiful. nice work @Ogutu-Brian

**Comment by Ogutu-Brian** [comment]
> Awesome Job

Thanks man!

**Comment by Ogutu-Brian** [comment]
> It is beautiful. nice work @Ogutu-Brian

Thanks @munniomer

**Comment by Ogutu-Brian** [comment]
> > Awesome Job
> 
> Thanks @Bakley

**Comment by jackiegitari1234** [comment]
Well done

**Comment by Ogutu-Brian** [comment]
> Well done

Thank you!

**Pull request merged**
