### PR TITLE
#162554630 A feature for viewing answers to questions(UI) 

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a page or feature that enables users to view answers to questions

### Description of Task to be completed?
Have the following goals achieved:
1. The feature needs to have an highlight of the question and various answers
2. The feature should be simple but detailed
4. The feature should be responsive
5. The feature should be appealing to the user

### How should this be manually tested?
1. Clone or fork the repo
2. checkout to  ft-view-answers-page-162554630 branch
3. change directory (cd) to UI
4. Open view.html using a browser

### Screenshots
screenshot from 2018-12-12 18-04-45
screenshot from 2018-12-12 18-05-21

### What is the relevant pivotal tracker stories?
#162554630

### CODE REVIEW

**Comment by MurungaKibaara** [comment]
In the first Question, there are two Q's.. other than that , I like what you've done, Good work! @Ogutu-Brian

**Comment by munniomer** [comment]
Nice work! thumbs up

**Comment by Ogutu-Brian** [comment]
> Nice work! thumbs up

Thanks @munniomer

**Comment by Ogutu-Brian** [comment]
> In the first Question, there are two Q's.. other than that , I like what you've done, Good work! @Ogutu-Brian
Thanks @MurungaKibaara , I didn't see that

**Comment by MachariaSolomon** [comment]
Good job.

**Comment by Ogutu-Brian** [comment]
> Good job.

Thanks @MachariaSolomon

**Comment by PaulKitonyi** [comment]
Nice UI. Keep it up, man.

**Comment by Ogutu-Brian** [comment]
> Nice UI. Keep it up, man.
Thanks @PaulKitonyi

**Comment by jackiegitari1234** [comment]
Good work. Keep it up

**Comment by Ogutu-Brian** [comment]
> Good work. Keep it up

Thanks @jackiegitari1234

**Pull request merged**
