### PR TITLE
#162693598 An endpoint for posting questions to StackOverflow-Lite (API)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a POST endpoint for posting questions to StackOverflow-Lite
### Description of Task to be completed?
Have the following endpoint working:
`1. POST /api/v1/questions`
'2. A client should with an account should be able to post a question to the platform`
`3. A client without an account should not be able to post a question to the platform`
`4. All the required fields from question model should be provided`
Ensure the passwords are encrypted

### How should this be manually tested?
After cloning the repo, create a virtual environment with `Python3.5.3`
1. activate virtual environment 
   `a. sudo apt-get install virtualenv`
   `b. python3.5 -m virtualenv virtualenvironment`
   `c. source virtualenvironment/bin/activate`
2. Install requirements
   `pip install -r requirements.txt` 
3. cd  Andela-StackOverflow-Lite/API
4. `python run.py`
5. Using postman or Insomnia, test the endpoint

### Screenshots
screenshot from 2018-12-17 12-04-48
screenshot from 2018-12-17 12-04-30

### What is the relevant pivotal tracker stories?
[#162693598](https://www.pivotaltracker.com/story/show/162693598)

### CODE REVIEW

**Comment by MurungaKibaara** [comment]
Fantabulous!!!!

**Comment by Ogutu-Brian** [comment]
> Fantabulous!!!!

Thanks @MurungaKibaara

**Comment by PaulKitonyi** [comment]
Hey, @Ogutu-Brian.Congratulations for the good work you have done. Please make sure you are not giving the user explicitly. Your API should be able to grab the session user. As you have written on your story this endpoint should be used or accessed by logged in user. Thanks.

**Comment by mawindavic** [comment]
Great Work @Ogutu-Brian

**Comment by Ogutu-Brian** [comment]
> Hey, @Ogutu-Brian.Congratulations for the good work you have done. Please make sure you are not giving the user explicitly. Your API should be able to grab the session user. As you have written on your story this endpoint should be used or accessed by logged in user. Thanks.

Thanks @PaulKitonyi , I will work on that

**Comment by Ogutu-Brian** [comment]
> Great Work @Ogutu-Brian

Thanks @oyando

**Pull request merged**
