### PR TITLE
#162554795 A feature for enabling a user to mark their answers as favourite (UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a page or feature that enables a user to mark the answers to their questions as favourite

### Description of Task to be completed?
Have the following goals achieved:
1. The feature should be simple and easy to be noticed by a user
2. The color of the feature should blend well with the page
4. The feature should be responsive
5. The feature should be appealing to the user
6. Use vanilla Js to handle the event of click on favorite button 

### How should this be manually tested?
1. Clone or fork the repo
2. checkout to  ft-best-answerr-selection-162554795  branch
3. change directory (cd) to UI
4. Open view.html using a browser

### Screenshots
screenshot from 2018-12-13 12-14-20
screenshot from 2018-12-13 12-14-47

### What is the relevant pivotal tracker stories?
[#162554795](https://www.pivotaltracker.com/story/show/162554795)

### CODE REVIEW

**Comment by PaulKitonyi** [comment]
Wow!!!!!Nice PR. The UI is also cool. You can consider making your PT id clickable so that one can easily navigate to your story.

**Comment by mawindavic** [comment]
Good combination of colors. Good job

**Comment by Ogutu-Brian** [comment]
> Wow!!!!!Nice PR. The UI is also cool. You can consider making your PT id clickable so that one can easily navigate to your story.

Suer, I will do that, thanks @PaulKitonyi

**Comment by Ogutu-Brian** [comment]
> Good combination of colors. Good job

Thanks @oyando

**Comment by jackiegitari1234** [comment]
Your choice of color is amazing

**Comment by Ogutu-Brian** [comment]
> Your choice of color is amazing

Thnks @jackiegitari1234

**Pull request merged**
