### PR TITLE
#162553605 A form or page for posting a question into StackOverflow-Lite(UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a page/form for posting questions to StackOverflow-Lite

### Description of Task to be completed?
Have the following goals achieved:
1. The look and feel should be appealing
2. The page should be responsive
3.The page should have enough fields required to post a question

### How should this be manually tested?
After cloning the repo open the ask.html file from a browser

### Screenshot
screenshot from 2018-12-12 09-11-13

### What is the relevant pivotal tracker stories?
#162553605

### CODE REVIEW

**Comment by munniomer** [comment]
@Ogutu-Brian kindly add a screenshot of your page so that we can review

**Comment by Ogutu-Brian** [comment]
> @Ogutu-Brian kindly add a screenshot of your page so that we can review

I haveadded a screenshot as requested

**Comment by jackiegitari1234** [comment]
Good work there

**Comment by Ogutu-Brian** [comment]
> Good work there

Thanks @jackiegitari1234

**Pull request merged**
