### PR TITLE
#162555021 A feature that enables users to do an up vote or a down vote to answers (UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a page or feature that enables a user to mark the answers to their questions as favourite

### Description of Task to be completed?
Have the following goals achieved:
1. The feature should be simple and easy to be noticed by a user
2. The color of the feature should blend well with the page
4. The feature should be responsive
5. The feature should be appealing to the user 

### How should this be manually tested?
1. Clone or fork the repo
2. checkout to  ft-best-answerr-selection-162554795  branch
3. change directory (cd) to UI
4. Open view.html using a browser

### Screenshots
screenshot from 2018-12-16 11-11-56
screenshot from 2018-12-16 11-13-37

### What is the relevant pivotal tracker stories?
[#162555021](https://www.pivotaltracker.com/story/show/162555021)

### CODE REVIEW

**Comment by ceexon** [comment]
Cool 
also responsive

**Comment by Ogutu-Brian** [comment]
> Cool
> also responsive

Thanks @kburudi

**Comment by PaulKitonyi** [comment]
Nice Ui Man.You also have a cool PR.Keep the fire burning

**Comment by Ogutu-Brian** [comment]
> Nice Ui Man.You also have a cool PR.Keep the fire burning

Thanks @PaulKitonyi

**Pull request merged**
