### PR TITLE
#162571758 A login page for StackOverflow-Lite(UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a log in page for StackOverflow-Lite platform

### Description of Task to be completed?
Have the following goals achieved:
1. The look and feel should be appealing
2. The page should be responsive
3. The page should have enough features needed for login 

### How should this be manually tested?
After cloning the repo open the login.html file from a browser

### Screenshot
screenshot from 2018-12-12 09-06-55

### What is the relevant pivotal tracker stories?
#162571758

### CODE REVIEW

**Comment by munniomer** [comment]
@Ogutu-Brian  kindly add a screenshot of your page so that we can review

**Comment by Ogutu-Brian** [comment]
> @Ogutu-Brian kindly add a screenshot of your page so that we can review

I have added that

**Comment by jackiegitari1234** [comment]
Nice

**Comment by Ogutu-Brian** [comment]
> Nice

Thanks @jackiegitari1234

**Pull request merged**
