### PR TITLE
#162552609 Sign up page (UI)

### PR DESCRIPTION
**Pull request by Ogutu-Brian**
### What does this PR do?
Have a sign up page for StackOverflow-Lite platform

### Description of Task to be completed?
Have the following goals achieved:
1. The look and feel should be appealing
2. The page should be responsive
3. The page should have enough features needed for a signup

### How should this be manually tested?
After cloning the repo open the register.html file with a browser

### What is the relevant pivotal tracker stories?
#162552609

> @Ogutu-Brian Kindly add the a screenshot of your Page

screenshot from 2018-12-12 09-15-49

### CODE REVIEW

**Comment by munniomer** [comment]
@Ogutu-Brian  Kindly add the a screenshot of your Page

**Comment by Ogutu-Brian** [comment]
> @Ogutu-Brian Kindly add the a screenshot of your Page

Added screenshot as requested

**Comment by jackiegitari1234** [comment]
i like the smooth input borders

**Comment by Ogutu-Brian** [comment]
> i like the smooth input borders

Thanks @jackiegitari1234 , I used border radius to smooth them

**Pull request merged**
